# This file was generated by GoReleaser. DO NOT EDIT.
cask "slimctl" do
  name "slimctl"
  desc "A CLI tool for managing SLIM Devices"
  homepage "https://github.com/lpuskas/slim/tree/main/control-plane/slimctl"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slimctl"

  on_macos do
    on_intel do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "970a5cd1ab699b2c59ba5608c5bd1eb4d100bfe7687301b68f7f046d09ec3c65"
    end
    on_arm do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "dc40dc0484077ea20e4a02868f2b9471ab4ab8d475d24120e2518c391e246b15"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl
      sha256 "1b0eb52d8ff75703fb813e12fa0d493da2a4ab8dff7f53ea449e6a5bd7d2631e"
    end
    on_arm do
      url "https://github.com/lpuskas/slim/releases/download/v#{version}/slimctl_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "7a758fc5202b4532dcf25f9415da3717a75f31ef91705ca531e4e3310a73e8ac"
    end
  end

  # No zap stanza required
end
