# This file was generated by GoReleaser. DO NOT EDIT.
cask "slimctl" do
  name "slimctl"
  desc "A CLI tool for managing SLIM Devices"
  homepage "https://github.com/lpuskas/slim/control-plane/slimctl"
  version "slimctl-v0.0.200-SNAPSHOT-0356b49"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slimctl"

  on_macos do
    on_arm do
      url "https://github.com/lpuskas/slim/releases/download/slimctl-v0.0.200/slimctl_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "4c7d54a6ec0be46fb91d00c24d3d4130d749eae97c70b14b8e209d5dc4452e60"
    end
  end

  postflight do
    system "chmod", "+x", "#{staged_path}/slimctl"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slimctl"]
    end
  end

  # No zap stanza required
end
